name: Build and Deploy Jekyll Site

on:
  push:
    branches: [ main ]

concurrency:
  group: pages-build-deploy
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true  # Automatic caching (no need for separate cache step)
          cache-version: 1     # Increment if you need to bust cache
- name: Cache gems
  uses: actions/cache@v3
  with:
    path: |
      vendor/bundle
      ~/.local/share/gem
    key: ${{ runner.os }}-ruby-${{ hashFiles('**/Gemfile.lock') }}
    restore-keys: |
      ${{ runner.os }}-ruby-

      - name: Build with Jekyll
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site